Adjust the topbar code so that the search button can be displayed in the top navigation on the mobile end 调整topbar代码,让搜索按钮可以在移动端显示在顶部导航

diff --git a/.direnv/bin/build b/.direnv/bin/build
--- a/.direnv/bin/build
+++ b/.direnv/bin/build
@@ -25,11 +25,11 @@ sed -i 's/\.\/lib\//\.\//g' lib/package.json
 fi
 
 
-# wait || \
-#   {
-#     echo "error : $?" >&2
-#     exit 1
-#   }
+wait || \
+  {
+    echo "error : $?" >&2
+    exit 1
+  }
 
 #find lib/ -name "*.svelte" -type f -print0 | xargs -0 touch
 
